char* chh;
int bspacectr;
unsigned int crow;

void clearLine(int row,int col);
void kmemcopy(void * dest,void * src,int n);
void halt();
//void deleteKey();
void console_clear();
void console_init();
void console_putc(char ch);
void bspetter(int fclr,int cl);
void displr(int nn,char* q,int clr);
void delClear(int color);
void sdoc(int nn);
void sdocone(int nn);
void sdoctwo(int nn);
void sdocthree(int nn);
void sdocfour(int nn);
void sdocfive(int nn);
void sdocsix(int nn);
void sdocseven(int nn);
void sdoceight(int nn);
void sdocnine(int nn);